export const  getProducts_Action ='getProducts_Action'
export const  addAmount_Action ='addAmount_Action'
export const  minusAmount_Action ='minusAmount_Action'
export const  changeCheckbox_Action ='changeCheckbox_Action'
export const  changeCheckedAll_Action ='changeCheckedAll_Action'
